### ISSUE TITLE
Error during build - can't find FMT

### ISSUE THREAD

**Issue by ghost** [Lugdunum3D/Lugdunum#118]
What am I doing wrong?
```
PS D:\Lab\Lugdunum\build> cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX="D:\Lab\Lugdunum-build" -DLUG_ACCEPT_DL=ON ../
-- Thirdparty hash: 995755d
-- Expected MD5 will be ''
-- Downloading https://thirdparty-dl.lugbench.eu/995755d/windows.zip
CMake Error at cmake/Macros.cmake:245 (file):
  file DOWNLOAD HASH mismatch

    for file: [D:/Lab/Lugdunum/build/thirdparty-995755d.zip]
      expected hash: []
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [7;"Couldn't connect to server"]

Call Stack (most recent call first):
  CMakeLists.txt:52 (lug_download_thirdparty)


-- Extracting...
-- Done!
-- Found Vulkan: C:/VulkanSDK/1.0.68.0/Lib/vulkan-1.lib
-- Could NOT find Fmt (missing: FMT_INCLUDE_DIR)
CMake Error at CMakeLists.txt:72 (message):
  Can't find fmt in the thirdparty directory


-- Configuring incomplete, errors occurred!
See also "D:/Lab/Lugdunum/build/CMakeFiles/CMakeOutput.log".
PS D:\Lab\Lugdunum\build>
```

**Comment by Sumenia** [comment]
We worked very hard on Lugdunum during two years, it was our end-of-study project. As of today, we finished our study and aren't maintaining it actively.

We had several dependancies and did a build system in order to automatically make CircleCI build them and send them to our server.

As of today, this server was shutdown, leading to this issue. You can build the dependancies manually with `https://github.com/Lugdunum3D/ThirdParty-Builder` repository. Or modify the CircleCi configuration file to point to a new server (`https://github.com/Lugdunum3D/Lugdunum/blob/dev/test/ci/scripts/circle_thirdparty.sh#L68`

Still up to answer any of your questions though, sorry for the delays 👍
