### ISSUE TITLE
Shaders (on models)?

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [Lugdunum3D/Lugdunum#45]
How would you go about applying shaders onto models, the only shaders i see are the light shaders and they are defined for loading in `Forward.cpp`.

Should I use Pipeline::createGraphicsPipeline too?

Is it also possible at this time to render 2D in the engine via shaders, if no. Will custom shaders be exposed to developers. Or will i have to make a fork?

Finally, is it possible to apply screenspace shaders? like color filters, etc.

**Comment by saveman71** [comment]
Hi!

First of all, thank you for your interest in Lugdunum!
As for your question, the thing is for now all is really just temporary as we are currently in the process of refactoring things in order to handle physical based rendering. For now, there are no materials at all (or a very basic notion of it).

We are also in the process of creating a builder pattern architecture for the different objects of the 3d engine, so `Pipeline::createGraphicsPipeline` will eventually go away.

We hope to have a functional beta available early July. For now, everything on the `dev` branch is not fixed or guaranteed to be stable; we'll merge `dev` to `master` as soon as we have something worth using ;)

If everything works out well, you'll eventually be able to apply a custom shader to a model!

Concerning the 2D aspect, we are in the process of implementing [imgui](https://github.com/ocornut/imgui) in our engine, in the branch [`feature-imgui-integration`](https://github.com/Lugdunum3D/Lugdunum/tree/feature-imgui-integration). We are doing that by creating a whole new pipeline

Kudos for creating the first "real" issue on the project!

PS: Documentation is coming soon on the [website](https://lugdunum3d.github.io/) as well, it's a top priority issue, especially if real users like you start looking into the project.

**Comment by LunaTheFoxgirl** [comment]
@saveman71 is there any way i can contribute. I'm aiming to use this as a backend for a game engine. c:

**Comment by saveman71** [comment]
Lugdunum is our end-of-study project, and we are currently refactoring some significant parts of the engine, and plans for the future are not publicly accessible as of now (but might be in the future?) so as of now I'm not sure how you could contribute.

However, bug fixes, feature requests, and general feedback are always appreciated.

After we release the beta version, things should slow down a bit architecture-wise, so it will be easier to contribute.
