### ISSUE TITLE
Log "spam" when rendering fails.

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [Lugdunum3D/Lugdunum#47]
Could Lugdunum hold a bit back with spamming the error messages, or have different error message modes which could be enabled or disabled. For example, when i tried creating a light, a bunch of error messages was repeatedly spammed into the logs, making it hard for me to read the logs over the spammed entries.

Possible solutions(?):
 * After a log entry has been repeated from the same source up to 5 times, the log will instead of spam just count up and for every 50 entry put the error message, prefixed with [x50]
 * Different debug modes that can be enabled and disabled for each log source?

(also sorry all of the issues im creating, if you want me to stop just say xD)

**Comment by Quentin01** [comment]
At the beginning, we planned to use different channels in order to allow the user to mute or configure each channel separately. In the final, this wasn't implemented like that and the logger is, for the moment, pretty dumb, it doesn't know anything about the source except the message.

I totally agree that this isn't the best way to implement a good logging system. So, one possible improvement could be to add this "channels feature" by passing the channel as a string to the logging function.

```cpp
logger.info("RendererVulkan: Can't load core vulkan functions"); // Old way
logger.info("RendererVulkan", "Can't load core vulkan functions"); // New way
```

Unfortunately, we are pretty busy for now because of all the features we need to finish before the beta. We will be able to improve the logging system after the release of the beta, or you can come with your pull request.

PS: What are the log messages that you got? Because I can't remember any error related to lights.

**Comment by LunaTheFoxgirl** [comment]
I will check the log messages when i get home, and i will make a pull request as well.

**Comment by LunaTheFoxgirl** [comment]
@Quentin01 Can you check the concept of such a system i made on my fork (https://github.com/Member1221/Lugdunum) my laptop does not support vulkan, so can't test the code here. Also it pushed alot of garbage which i will remove if i make a PR

**Comment by LunaTheFoxgirl** [comment]
Also, i realised that i used fmt wrong. Never used the library, other than in golang. I will fix my mistakes in the code. xD

**Comment by Quentin01** [comment]
My personal opinion is that it is maybe better to mute a channel according to the level than just mute or unmute it. It seems like @saveman71 also agrees with that.

Something like that:
```cpp
logger.setSourceLevel("Foo", Level::Off); // Completely mute the channel
logger.setSourceLevel("Foo", Level::Error); // Only display Error, Fatal, Assert
```

By the way, I know that it's not a definitive source code, but we have a guideline (not a public one for the moment, but it will be public soon). But don't worry, if you make a PR we will review it to tell you if there is any mistake ;)

(minor grammatical edits by @saveman71, sorry :s)

**Comment by LunaTheFoxgirl** [comment]
Okies, will do c:

**Comment by Quentin01** [comment]
I was mistaken, a version of the guideline is available on the branch `dev` (not the final one, but there isn't a lot of change since). https://github.com/Lugdunum3D/Lugdunum/blob/dev/doc/guidelines.md

**Comment by LunaTheFoxgirl** [comment]
Okay, i will read it through.

**Comment by LunaTheFoxgirl** [comment]
I've applied some changes and fixed some stuff, would you mind checking if i've done the code style correctly?
I only need to make all of Lugdunum use logs correctly now x,D

**Comment by Quentin01** [comment]
Now that you have open a PR (#48), we can discuss on it, that will be easier.
